name: TangoStar
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - pytorch-cuda
  # - cuda-toolkit
  - networkx
  - python-graphviz
  - numpy
  - scipy
  - pandas
  - tqdm
  - faiss-gpu
  - pip:
    - rdkit
    - rdchiral
    - psutils
    - torch<=2.6
